apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-node1
spec:
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data-pv  # Asegúrate que esta ruta existe en cada nodo
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - anx-tv-control-plane

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-node2
spec:
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data-pv  # Asegúrate que esta ruta existe en cada nodo
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - anx-tv-control-plane2

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-node3
spec:
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data-pv  # Asegúrate que esta ruta existe en cada nodo
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - anx-tv-worker

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-node4
spec:
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data-pv  # Asegúrate que esta ruta existe en cada nodo
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - anx-tv-worker2

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-node5
spec:
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data-pv  # Asegúrate que esta ruta existe en cada nodo
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - anx-tv-worker3