apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: prod
type: Opaque
data:
  user-password: c2VjcmV0
  root-password: c2VjcmV0

---

apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: prod
type: Opaque
data:
  access-key: cm9vdAo=
  secret-key: ZDEyNGUwY2UzMAo=