apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minio
  name: minio
  namespace: prod # Change this value to match the namespace metadata.name
spec:
  containers:
  - name: minio
    image: quay.io/minio/minio:latest
    command:
    - /bin/bash
    - -c
    args: 
    - minio server /data --console-address :9090
    env:
    - name: MINIO_ROOT_USER
      value: root
    - name: MINIO_ROOT_PASSWORD
      value: d124e0ce30
    volumeMounts:
    - mountPath: /data
      name: localvolume # Corresponds to the `spec.volumes` Persistent Volume
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "700m"
  volumes:
  - name: localvolume
    hostPath: # MinIO generally recommends using locally-attached volumes
      path: /run/desktop/mnt/host/c/kubernetes-pv-video # Specify a path to a local drive or volume on the Kubernetes worker node
      type: DirectoryOrCreate # The path to the last directory must exist

---

apiVersion: v1
kind: Service
metadata:
  namespace: prod
  name: minio
  labels:
    app: minio
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: webui
      port: 9090
      targetPort: 9090
  selector:
    app: minio

---

apiVersion: v1
kind: Service
metadata:
  namespace: prod
  name: minio-external
  labels:
    app: minio
spec:
  type: NodePort
  ports:
    - name: webui
      port: 9090
      targetPort: 9090
      nodePort: 30001
    - name: api
      port: 9000
      targetPort: 9000
      nodePort: 30002
  selector:
    app: minio