apiVersion: v1
kind: Service
metadata:
  namespace: prod
  name: anx-tv-backend-service
spec:
  type: NodePort
  selector:
    app: anx-tv-backend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000