apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
  - 01-pv.yaml
  - 02-secret.yaml
  - 03-storage-class.yaml
  - 04-database.yaml
  - 05-deployment.yaml
  - 06-service.yaml

namespace: prod