kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: anx-tv
nodes:
    # Primer nodo control-plane que también actuará como worker
  - role: control-plane
    extraPortMappings:
      - containerPort: 30002  # Puerto en el nodo de kind (NodePort)
        hostPort: 30002     # Puerto en tu PC (desde donde accederás)
        listenAddress: "0.0.0.0"  # Escucha en todas las interfaces
        protocol: tcp
      - containerPort: 30001  # Puerto en el nodo de kind (NodePort)
        hostPort: 30001      # Puerto en tu PC (desde donde accederás)
        listenAddress: "0.0.0.0"  # Escucha en todas las interfaces
        protocol: tcp
      - containerPort: 30000  # Puerto en el nodo de kind (NodePort)
        hostPort: 30000      # Puerto en tu PC (desde donde accederás)
        listenAddress: "0.0.0.0"  # Escucha en todas las interfaces
        protocol: tcp
      - containerPort: 80  # Puerto en el nodo de kind (NodePort)
        hostPort: 80      # Puerto en tu PC (desde donde accederás)
        listenAddress: "0.0.0.0"  # Escucha en todas las interfaces
        protocol: tcp
  
  - role: worker
  
  # Tres nodos workers
  - role: worker
  - role: worker
  - role: worker